name = "Terra Aeterna"
author = "Terra Aeterna Team"
version = "1.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "611ed905c6669bdebf0dc6ea4f0bf6415cfdecb6f16005bb3173ebf7a5dcf587"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
