["Legendary Beasts"]
	#0 means disabled, 1 means enabled
	"Mushlin King Spawning" = true
	"Piglin Executioner Spawning" = true
	"Furnace Spawning" = true
	#Rare beast spawn configurations require true/false values
	"Rare Furnace Spawning" = true
	"Rare Mushlin king Spawning" = true
	"Rare Piglin Executioner Spawning" = true

["Legendary Items"]
	#The value in half hearts recovered after using the spore bundle (default is 6)
	"Spore Bundle Healing" = 6.0
	#Sets the amount of seconds the player is effected with 'antidote' after using the Spore Bundle (Default is 20)
	"Spore Bundle Antidote" = 20.0
	#Sets the amount of seconds the player receives strength for after killing a mob (default is 2)
	"Executioner Cowl Strength" = 2.0
	#Sets the amount of seconds between damage ticks of the Molten Coal (Default is 3)
	"Molten Coal Damage timer" = 3.0

[Other]
	#Totem of Beasts range (default is 100)
	"Beast Totem Range" = 100.0
	#Determines the amount of hitpoints an auto mending repair heals for (default is 100)
	"Auto Mending Restoration" = 100.0
	#Sets the amount of seconds (in ticks) crimson contaminant infects for (default is 300)
	"Hemorrhage Timer" = 300.0
	#Determines if the Luminous:Tag startup message appears
	"Startup Message" = true

[Rituals]
	#Enter the item registry name of any items you do NOT want to be affected by the auto mending ritual
	"Mending Blacklist Item One" = ""
	"Mending Blacklist Item Two" = ""
	"Mending Blacklist Item Three" = ""
	"Mending Blacklist Item Four" = ""
	"Mending Blacklist Item Five" = ""

["Mob Spawns"]
	#Determines if Crimson Walkers will Spawn in your world
	"Crimson Walker Spawns" = true
	#Determines if Revenants will Spawn in your world
	"Revenant Spawns" = true
	#Determines if Zombified Piglin Cultists will Spawn in your world
	"Zombified Cultist Spawns" = true
	#Determines if Piglin Cultists will Spawn in your world
	"Cultist Spawns" = true
	#Determines if Mushlin Bumpers will Spawn in your world
	"Mushlin Spawns" = true
	#Determines if Piglin Ghosts will Spawn in your world
	"Piglin Ghost Spawns" = true
	#Determines if Spirits will Spawn in your world
	"Spirit Spawns" = true
	#Determines if Guzzleghasts will Spawn in your world
	"Guzzleghast Spawns" = true

["Ritual Cooldowns"]
	#Sets the number (in minutes) for each cooldown
	"Ritual of Health Cooldown" = 3.0
	"Ritual of Cleansing Cooldown" = 3.0
	"Ritual of Night Cooldown" = 6.0
	"Ritual of Chance Cooldown" = 2.0
	"Ritual of Saturation Cooldown" = 8.0
	"Ritual of Experience Cooldown" = 10.0
	"Ritual of Perception Cooldown" = 10.0
	"Ritual of Mending Cooldown" = 30.0
	"Ritual of Luck Cooldown" = 10.0
	"Ritual of Sanctuary Cooldown" = 10.0

["Active / Inactive Rituals"]
	#when set to false, any of the below Rituals will not appear in the normal rotation
	"Ritual of Health" = true
	"Ritual of Cleansing" = true
	"Ritual of Night" = true
	"Ritual of Chance" = true
	"Ritual of Saturation" = true
	"Ritual of Experience" = true
	"Ritual of Perception" = true
	"Ritual of Mending" = true
	"Ritual of Luck" = true
	"Ritual of Sanctuary" = true
