[client]
	#Lifetime in ticks for detached gibs.
	# Default: 1000
	# Range: 0 ~ 20000
	gibTime = 1000
	#Time in ticks that a gib can remain on the ground before fading.
	# Default: 100
	# Range: 0 ~ 20000
	gibGroundTime = 100
	#Render blood particles on dismemberment.
	blood = true
	#Amount of particles per blood burst.
	# Default: 20
	# Range: 1 ~ 1000
	bloodCount = 20
	#Spawn occasional extra blood spurts from the wound while the mob is still alive.
	bloodSplurt = true
	#Keeps blood particles spawning indefinitely. May reduce FPS.
	infiniteBloodParticles = false
	#Use green blood for non-player mobs.
	greenBlood = false
	#Render detached limbs for other players when the server allows it.
	showPlayerGibs = true
