[items_toggle]
	enable_placeable_bowl = true
	enable_placeable_apple = true
	enable_placeable_bakedpotato = true
	enable_placeable_beef = true
	enable_placeable_beetroot = true
	enable_placeable_beetrootsoup = true
	enable_placeable_beetrootseeds = true
	enable_placeable_blazepowder = true
	enable_placeable_book = true
	enable_placeable_bone = true
	enable_placeable_bow = true
	enable_placeable_bread = true
	enable_placeable_brick = true
	enable_placeable_carrot = true
	enable_placeable_carrotonastick = true
	enable_placeable_charcoal = true
	enable_placeable_chicken = true
	enable_placeable_chorusfruit = true
	enable_placeable_clayball = true
	enable_placeable_coal = true
	enable_placeable_cookedbeef = true
	enable_placeable_cookedchicken = true
	enable_placeable_cookedmutton = true
	enable_placeable_cookedporkchop = true
	enable_placeable_cookedrabbit = true
	enable_placeable_cookie = true
	enable_placeable_copperingot = true
	enable_placeable_diamond = true
	enable_placeable_diamondaxe = true
	enable_placeable_diamondhoe = true
	enable_placeable_diamondpickaxe = true
	enable_placeable_diamondshovel = true
	enable_placeable_diamondsword = true
	enable_placeable_dragonbreath = true
	enable_placeable_egg = true
	enable_placeable_emerald = true
	enable_placeable_enchantedbook = true
	enable_placeable_endereye = true
	enable_placeable_enderpearl = true
	enable_placeable_experiencebottle = true
	enable_placeable_feather = true
	enable_placeable_firecharge = true
	enable_placeable_fireworkrocket = true
	enable_placeable_glassbottle = true
	enable_placeable_glisteringmelonslice = true
	enable_placeable_goldingo = true
	enable_placeable_goldenaxe = true
	enable_placeable_goldencarrot = true
	enable_placeable_goldenhoe = true
	enable_placeable_goldenpickaxe = true
	enable_placeable_goldenshovel = true
	enable_placeable_goldensword = true
	enable_placeable_heartofthesea = true
	enable_placeable_honeybottle = true
	enable_placeable_ironaxe = true
	enable_placeable_ironhoe = true
	enable_placeable_ironingot = true
	enable_placeable_ironpickaxe = true
	enable_placeable_ironshovel = true
	enable_placeable_ironsword = true
	enable_placeable_lavabucket = true
	enable_placeable_lingeringpotion = true
	enable_placeable_leather = true
	enable_placeable_magmacream = true
	enable_placeable_melonslice = true
	enable_placeable_milkbucket = true
	enable_placeable_mushroomstew = true
	enable_placeable_music_disc = true
	enable_placeable_mutton = true
	enable_placeable_netherbrick = true
	enable_placeable_netheriteaxe = true
	enable_placeable_netheritehoe = true
	enable_placeable_netheritepickaxe = true
	enable_placeable_netheriteshovel = true
	enable_placeable_netheritesword = true
	enable_placeable_netheriteingot = true
	enable_placeable_poisonouspotato = true
	enable_placeable_poppedchorusfruit = true
	enable_placeable_porkchop = true
	enable_placeable_potion = true
	enable_placeable_potato = true
	enable_placeable_pumpkinpie = true
	enable_placeable_rabbit = true
	enable_placeable_rabbitstew = true
	enable_placeable_rottenflesh = true
	enable_placeable_slimeball = true
	enable_placeable_snowball = true
	enable_placeable_spidereye = true
	enable_placeable_splashpotion = true
	enable_placeable_suspiciousstew = true
	enable_placeable_stoneaxe = true
	enable_placeable_stonehoe = true
	enable_placeable_stonepickaxe = true
	enable_placeable_stoneshovel = true
	enable_placeable_stonesword = true
	enable_placeable_waterbucket = true
	enable_placeable_wheat = true
	enable_placeable_woodenaxe = true
	enable_placeable_woodenhoe = true
	enable_placeable_woodenpickaxe = true
	enable_placeable_woodenshovel = true
	enable_placeable_woodensword = true
	enable_placeable_writableboo = true
	enable_placeable_writtenbook = true
	enable_placeable_bucket = true
