maxSavedRecordings = 200
minimumAudioCount = 50
# Default: 12
# Range: 1 ~ 100
revervoxMaxAudios = 12
# Default: 1.5
# Range: 0.0 ~ 5.0
revervoxGracePeriod = 1.5
# Default: 0.5
# Range: 0.0 ~ 5.0
revervoxBatGracePeriod = 0.5
# Default: 5
# Range: 2 ~ 500
revervoxBatSpawnChance = 5
# Default: 7
# Range: 1 ~ 20
revervoxSwordBonus = 7
# Default: 10
# Range: 1 ~ 20
batToothDropChance = 10
# Default: 100
# Range: 0 ~ 500
revervoxMinimumDistance = 100
# Default: 1.0
# Range: 0.1 ~ 20.0
batEventChance = 1.0
enableBatEvent = false
revervoxBlockBreaking = false
revervoxAboveGround = false
revervoxBreakNonSolid = true
revervoxSonicBoom = true
# Default: 5
# Range: 1 ~ 100
revervoxSonicBoomCooldown = 5
# Default: 30
# Range: 10 ~ 100
revervoxSonicBoomRange = 30
# Default: 4
# Range: 0 ~ 100
megaphoneCooldown = 4
crouchStopsMegaphone = true
